name: CI
on: [push]

env:
  DOCKER_IMAGE: sammreen
  DOCKER_TAG: latest  

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
        
      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Deploy Docker container
        run: |
          docker stop sammreen || true
          docker rm sammreen || true
          docker run -d --name sammreen -p 81:81 ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          docker ps
          docker logs sammreen

  test:
    runs-on: self-hosted
    needs: deploy
    container:
      image: curlimages/curl:latest
    steps:
      - name: Test if the server is up
        run: |
          sleep 180  # Increase sleep time to allow the server to be ready
          curl -v http://103.172.26.37:81 || true
          test $(curl -s -o /dev/null -w "%{http_code}" http://103.172.26.37:81) -eq 200
