name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t sammreen .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:     
      - name: Deploy Docker container
        run: |
          echo "Deploying Docker container..."
          docker stop sammreen || true
          docker rm sammreen || true
          docker run -d --name sammreen -p 81:81 sammreen

  test:
    runs-on: self-hosted
    needs: deploy
    container:
      image: curlimages/curl:latest
    steps:
      - name: Test if the server is up
        run: |
          echo "Waiting for the server to be up..."
          sleep 180  
          
          echo "Checking server response..."
          MAX_RETRIES=5
          RETRY_INTERVAL=30

          for i in $(seq 1 $MAX_RETRIES); do
            RESPONSE_CODE=$(curl -s --max-time 60 -o /dev/null -w "%{http_code}" http://103.172.26.37:81)
            if [ "$RESPONSE_CODE" -eq 200 ]; then
              echo "Server is up and running."
              exit 0
            else
              echo "Attempt $i: Server is not up. HTTP code: $RESPONSE_CODE"
              sleep $RETRY_INTERVAL
            fi
          done
          
          echo "Server did not respond with HTTP 200 after $MAX_RETRIES attempts."
          exit 1
