name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t sammreen .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:     
      - name: Deploy Docker container
        run: |
          echo "Deploying Docker container..."
          docker stop sammreen || true
          docker rm sammreen || true
          docker run -d --name sammreen -p 81:81 sammreen

  test:
    runs-on: self-hosted
    needs: deploy
    container:
      image: curlimages/curl:latest
    steps:
      - name: Test if the server is up
        run: |
          sleep 60
          curl -v http://103.172.26.37:81 || true
          test $(curl -s -o /dev/null -w "%{http_code}" http://103.172.26.37:81) -eq 200
  
